apiVersion: v2
name: scoutflow
description: A Helm chart for ScoutFlow
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nba
  - statistics
  - tracker
maintainers:
  - name: Omer Beit Halahmy
    email: beithalahmyomer@gmail.com