apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: config
data:
  DB_HOST: {{ .Release.Name }}-db
  DB_PORT: "5432"
  DB_NAME: {{ .Values.database.env.POSTGRES_DB | quote }}