# ============================================================================
# ECR Registry Secret
# Configures authentication credentials for pulling images from AWS ECR
# ============================================================================

{{- if .Values.ecr.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values.imagePullSecrets 0 "name" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

{{- define "imagePullSecret" }}
{{- printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.global.registry (printf "%s:%s" .Values.ecr.username .Values.ecr.password | b64enc) | b64enc }}
{{- end }}
