apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  DB_USER: {{ .Values.database.env.POSTGRES_USER }}
  DB_PASSWORD: {{ .Values.database.env.POSTGRES_PASSWORD }}