apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-app-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: serviceaccount
